id = "sqlite"
name = "SQLite"
schema_version = 1
version = "1.2.6"
authors = ["ytrytio"]
description = "SQLite language support."
repository = "https://github.com/ytrytio/sqlite"

[grammars.sqlite]
repository = "https://github.com/dhcmrlchtdj/tree-sitter-sqlite"
rev = "main"
